name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
  publish-snapshot:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up settings.xml for Github Packages
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Publish SNapshot to github packages
        run: mvn -B --no-transfer-progress deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}