name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up settings.xml for Github Packages
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{github.run_number}}
          release_name: Release V${{github.run_number}}

      - name: Update version
        run: mvn -B versions:set -DnewVersion=v${{github.run_number}} -DgenerateBackupPoms=false

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B deploy -DskipTests --file pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}